### ISSUE TITLE
modulos vteApp.auth e vteApp.admin não disponíveis 

### ISSUE THREAD

**Issue by marcomafessolli** [cmmit/vte#2]
A aplicação dispara os errors: 

`Uncaught Error: [$injector:nomod] Module 'vteApp.auth' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.`

e

`Uncaught Error: [$injector:nomod] Module 'vteApp.admin' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.`

**Comment by pedro-ramos** [comment]
https://github.com/angular-fullstack/generator-angular-fullstack/issues/1552

Resolvido neste pull request: https://github.com/cmmit/vte/pull/3

Embora não haja solução definitiva do próprio generator-angular-fullstack, já está resolvido neste projeto.
